invertase/flutterfire_cli

- packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart
> chore: refactor the generated switch-case

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_app_id_file.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart
Continuation on #43 to add support for Android
> feat: updates configure to also write out Android app ID files

- packages/flutterfire_cli/lib/src/common/exception.dart
- change "already exists" to "already up to date"
> refactor: change messaging of already exists

- packages/flutterfire_cli/bin/flutterfire.dart
this should only log if it updates.
> fix: move autoupdater log inside conditional

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_android_gradle_plugins.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_web_options.dart
- packages/flutterfire_cli/lib/src/flutter_app.dart
> feat: add support for Windows & Linux platforms via Firebase Web apps.

- packages/flutterfire_cli/lib/src/commands/config.dart
> feat: add new `--platforms` flag to specify platforms to generate Firebase options for without prompts (Closes #68)

- packages/flutterfire_cli/pubspec.yaml
> feat: Upgrade version of xml

- packages/flutterfire_starter/hooks/post_gen.dart
- packages/flutterfire_starter/hooks/pre_gen.dart
- refactor(hooks): remove deprecated templating
> refactor(hooks): remove deprecated templating

- packages/flutterfire_cli/lib/src/command_runner.dart
- packages/flutterfire_cli/lib/src/commands/update.dart
Often users will face issues updating to corresponding versions of the plugins.
Since a BOM system cannot be introduced without significantly impacting build size, we introduce `flutterfire update` to help user properly update to the latest versions
> feat: add a `flutterfire update` command

- packages/flutterfire_cli/lib/src/firebase/firebase_apple_setup.dart
Updates `firebase.json` on second run of `flutterfire configure` as reported here:
https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1422651481
> fix: update json on subsequent runs of `flutterfire configure`

- .github/workflows/validate.yaml
- melos.yaml
- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/test/flutterfire_cli_test.dart
- packages/flutterfire_cli/test/test_files/firebase_options.dart
- packages/flutterfire_starter/__brick__/lib/src/sample_feature/sample_item_details_view.dart
- packages/flutterfire_starter/test/flutterfire_starter_test.dart
First integration test for FFCLI. Checks everything that occurs on running `flutterfire configure`, including:
- Service file writes for apple (`GoogleService-Info.plist`) & android (`google-services.json`).
- `firebase_options.dart` write for Flutter project.
- Checks scripts have been created for Xcode project in build phase run scripts for Crashlytics debug symbols script and for bundling service file with app resources.
- Checks `firebase.json` write in root of Flutter project.
- Checks `build.gradle` updates have occurred.
I have removed windows runner for now until I have time to test it on a Windows machine.
> test: first e2e test for "flutterfire configure" basic command

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/common/strings.dart
- packages/flutterfire_cli/lib/src/common/utils.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_android_gradle_plugins.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_apple_setup.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart
- packages/flutterfire_cli/test/flutterfire_cli_test.dart
- packages/flutterfire_cli/test/test_files/default_firebase.json
This PR:
- ensures "firebase.json" is updated correctly. 
- validates service file path (android) and name.
I'm going to base of this branch. Next parts:
- auto detecting crashlytics and remove prompt & argument for adding debug symbols.
- creating new command for updating service files `flutterfire config-update`.
> feat: update "firebase.json" values for web, android and apple. Updated validation for service files for android & apple.

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/common/validation.dart
- packages/flutterfire_cli/test/configure_test.dart
> fix: Dart configuration output is respected if selected as argument

- packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart
- packages/flutterfire_cli/test/test_utils.dart
Firebase docs recommend google services version be `4.3.15`:
https://firebase.google.com/docs/android/setup#add-config-file
closes: https://github.com/invertase/flutterfire_cli/issues/199
> fix: update google services version dependency for android

- packages/flutterfire_cli/lib/src/firebase.dart
related to: https://github.com/invertase/flutterfire_cli/issues/30
> fix: diagnostic try/catch around erroneous JSON response

- CHANGELOG.md
- melos.yaml
- packages/flutterfire_cli/CHANGELOG.md
- packages/flutterfire_cli/pubspec.yaml
- packages/flutterfire_starter/hooks/pubspec.yaml
Latest release for FlutterFire CLI - `0.3.0-dev.17`
> chore(release): prepare for release 

- packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart
- packages/flutterfire_cli/test/configure_test.dart
- packages/flutterfire_cli/test/test_utils.dart
Noticed a previous change made, was writing `build.gradle` content on the same line. Fixed bug and also updated tests to check content is written on new lines.
> fix: ensure `build.gradle` content is written on new lines

- CHANGELOG.md
- packages/flutterfire_cli/CHANGELOG.md
- packages/flutterfire_cli/pubspec.yaml
- packages/flutterfire_starter/hooks/pubspec.yaml
> chore(release): prepare for release

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/test/configure_test.dart
- packages/flutterfire_cli/test/reconfigure_test.dart
- packages/flutterfire_cli/test/test_utils.dart
> test: fail when `Process.run` fails and output the stderr

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart
> chore: clean up unused `force` flag for android writes

- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/test/configure_test.dart
- packages/flutterfire_cli/test/reconfigure_test.dart
- packages/flutterfire_cli/test/test_files/firebase_options.dart
- packages/flutterfire_cli/test/test_utils.dart
> fix: ensure `--web-app-id` flag is respected when present in `flutterfire configure`

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/commands/reconfigure.dart
- packages/flutterfire_cli/lib/src/common/utils.dart
- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_dart_configuration_write.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_platform_options.dart
- packages/flutterfire_cli/test/configure_test.dart
- packages/flutterfire_cli/test/reconfigure_test.dart
- packages/flutterfire_cli/test/test_utils.dart
closes https://github.com/invertase/flutterfire_cli/issues/219
> feat: windows support for `flutterfire configure` & `flutterfire reconfigure`

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart
fixes https://github.com/invertase/flutterfire_cli/issues/236
> fix(android): update regex as `android/build.gradle` in latest flutter create doesn't match previous regex

- packages/flutterfire_cli/lib/src/commands/config.dart
- packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart
Check if `GoogleService-Info.plist` resource already exists in `project.pbxproj` setup (imagine multiple calls to `flutterfire configure`). If it exists, we only need to rewrite the file, not update `project.pbxproj`.
fixes https://github.com/invertase/flutterfire_cli/issues/235
> fix(apple): ensure service file is not duplicated in `project.pbxproj` file

- CHANGELOG.md
- README.md
- packages/flutterfire_cli/CHANGELOG.md
- packages/flutterfire_cli/lib/version.g.dart
- packages/flutterfire_cli/pubspec.yaml
- packages/flutterfire_starter/hooks/pubspec.yaml
> chore: prepare for release

- packages/flutterfire_cli/pubspec.yaml
- pubspec.yaml
> chore: upgrade dependencies

- packages/flutterfire_cli/lib/src/common/strings.dart
- packages/flutterfire_cli/lib/src/common/utils.dart
- packages/flutterfire_cli/lib/src/firebase.dart
- packages/flutterfire_cli/test/unit_tests.dart
…
fixes https://github.com/invertase/flutterfire_cli/issues/262
> fix: firebase CLI can sometimes append time out object on successful JSON response.

- packages/flutterfire_cli/lib/src/commands/install.dart
> feat: add support for Vertex AI in the install command

- CHANGELOG.md
- packages/flutterfire_cli/CHANGELOG.md
- packages/flutterfire_cli/lib/version.g.dart
- packages/flutterfire_cli/pubspec.yaml
- packages/flutterfire_starter/hooks/pubspec.yaml
> chore(release): publish packages

- CONTRIBUTING.md
- melos.yaml
FFCLI own release process including generating version number for CLI.
> chore: update release process & include generated CLi version script

- packages/flutterfire_cli/lib/src/commands/install.dart
… _web packages when using git
> feat(install): add support for overriding the _platform_interface and _web packages when using git

- README.md
> docs: update docs for developing FlutterFire CLI

- packages/flutterfire_cli/test/install_test.dart
> ci: fix integration tests

- packages/flutterfire_cli/lib/src/flutter_app.dart
> fix(android): auto-detect old and new way to set `applicationId`

- packages/flutterfire_cli/lib/src/commands/install.dart
Linked to: https://github.com/firebase/flutterfire/pull/13127
> feat: update to support main on the FlutterFire repository

- .github/workflows/issue-labels.yaml
> chore: add issue labels workflow

- .github/workflows/issue-labels.yaml
- .github/workflows/stale-issue.yaml
> chore: update label management

- README.md
> docs: multi flavor setup link

- CONTRIBUTING.md
> docs: update contributing documentation so users clone rather than fork

- packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart
Resolves https://github.com/invertase/flutterfire_cli/issues/386
Adds `PUB_CACHE` for the path extension.
> feat: Adds `PUB_CACHE` for Apple writes

- .github/workflows/validate.yaml
> ci: fix broken test due to experimental flag pre Xcode v16.2
