invertase/flutterfire_cli

packages/flutterfire_cli/lib/src/firebase.dart
Without it, it would throw the error: `ProcessException: The system cannot find the file specified.`
I used `Platform.isWindows` instead of `true` as I am not sure of the implications of this on other systems.
Supposedly fixes #3
=> fix: Add `runInShell` when running on Windows

.github/workflows/pr_title.yaml
Upgrade version of the [`action-semantic-pull-request`](https://github.com/amannn/action-semantic-pull-request) GitHub Action, which validates that PR titles match the [Conventional Commits spec](https://www.conventionalcommits.org/).
At the moment (`flutterfire_cli v0.1.1+2`), any PR includes i̶s̶ r̶e̶j̶e̶c̶t̶e̶d̶ a̶n̶d̶ m̶a̶r̶k̶e̶d̶ a̶s̶ *̶*̶F̶a̶i̶l̶i̶n̶g̶*̶*̶ d̶u̶e̶ t̶o̶  a deprecation notice thrown by the `2.1.0` version of the action.
More info [here](https://github.com/amannn/action-semantic-pull-request/issues/62).
=> ci: bump conventional PR title checker version

packages/flutterfire_cli/lib/src/commands/config.dart
- deprecated android-application-id in configure command in favour of android-package-name.
=> refactor: deprecate `android-application-id` in favour of `android-package-name`

packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/firebase.dart, packages/flutterfire_cli/lib/src/firebase/firebase_android_gradle_plugins.dart, packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart
Adds support to auto apply Crashlytics & Performance Android Gradle plugins. This can be disabled via the hidden `--no-apply-gradle-plugins` flag.
=> feat: add support to auto apply Crashlytics & Performance Android Gradle plugins

packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/common/utils.dart
I noticed whilst debugging this [issue](https://github.com/firebase/flutterfire/issues/9400) that initialization was occurring from the dart config file, not the `GoogleService-Info.plist` file. It appears Firebase will not pick up the file unless it is added to the target.
I also think we should stop writing the config to the `DefaultFirebaseOptions` class for android & iOS. Unnecessary and, I think, confusing to users.
=> fix: `GoogleService-Info.plist` file not found by Firebase SDK unless added to target

packages/flutterfire_cli/lib/src/firebase/firebase_project.dart
This fixes #86 by reusing the projectId as the displayName when a displayName is null. This is because displayName is an optional field for projects. See the following link for more information: https://cloud.google.com/resource-manager/reference/rest/v1/projects#Project.FIELDS.name
=> fix: reuse projectId when displayName is null on configure

packages/flutterfire_cli/lib/src/common/utils.dart
When manually adding `GoogleService-Info.plist` to your XCode project, the file gets added to the project as a bundle resource file and gets added to the `Copy Bundle Resources` build phase for the target.
The Ruby script however was adding the file as a compile source file and as such was being added to the `Compile Sources` build phase for the target.
This was causing issues with macOS in #123 and this brings it in-line with the Firebase documentation and the expected way of adding `GoogleService-Info.plist` to the project.
Fixes #123.
=> fix: add GoogleService-Info.plist as bundle resource not compile source

packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/firebase.dart, packages/flutterfire_cli/lib/src/firebase/firebase_web_options.dart
Add the option `web-app-id` to allow users to select which of the web apps they want to use. Didn't use `display-name` as that can easily be changed from Firebase's side, which could cause issues. 
- Ask user to select when not in CI
- The behaviour used in this option can later be extrapolated to be used for linux and windows apps as well.
resolves #77
=> feat: Allow selecting web app id

README.md
Update to not refer to the Flutter SDK for Firebase as FlutterFire anymore, and to link to the official documentation.
=> docs: Update README.md to not refer to the Flutter SDK for Firebase as FlutterFire anymore

packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/common/strings.dart, packages/flutterfire_cli/lib/src/common/utils.dart, packages/flutterfire_cli/lib/src/firebase/firebase_configuration_file.dart, packages/flutterfire_cli/lib/src/firebase/firebase_ios_setup.dart, packages/flutterfire_cli/lib/src/firebase/firebase_macos_setup.dart
Created command line arguments which negate the need to use the command prompts. The following command line arguments have been added:
1. `ios-scheme` - pass in the name of the scheme you wish to use for your iOS project.
2. `macos-scheme` - pass in the name of the scheme you wish to use for your macOS project.
3. `ios-target`- - pass in the name of the target you wish to use for your iOS project.
4. `macos-target`- - pass in the name of the target you wish to use for your macOS project.
5. `debug-symbols-ios` - This is a command line flag.  It will add an upload debug symbols script to your iOS target or scheme (depending on whether you used `ios-scheme` or `ios-target`). This replaces `debug-symbols-script` which was a hidden flag in the last dev release. If you choose to negate the …
=> feat(cli): command line arguments for different environments

melos.yaml
`flutter format` shouldn't be used anymore:
```
[!] The "format" command is deprecated and will be removed in a future version of Flutter. Please use the "dart format" sub-command instead,
which takes all of the same command-line arguments as "flutter format".
```
=> ci(*): use `dart format` instead of `flutter format`

packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/commands/reconfigure.dart, packages/flutterfire_cli/lib/src/common/strings.dart, packages/flutterfire_cli/lib/src/common/validation.dart, packages/flutterfire_cli/lib/src/firebase/firebase_apple_setup.dart, packages/flutterfire_cli/test/configure_test.dart, packages/flutterfire_cli/test/reconfigure_test.dart, packages/flutterfire_cli/test/test_utils.dart
Update includes:
1. Updated implementation so apple service files are always rewritten. 
2. Wrote an e2e test to prove service files and JSON files are rewritten if running "flutterfire configure" twice.
3. Refactored code for apple so we reuse functions.
4. Ensure dart config file rewrite doesn't prompt when passing `--yes` argument.
closes https://github.com/invertase/flutterfire_cli/issues/109
=> feat: overwrite Apple service files if they exist already.

packages/flutterfire_cli/lib/src/common/strings.dart, packages/flutterfire_cli/lib/src/firebase/firebase_apple_setup.dart
This PR removes absolute paths from polluting the Xcode project. It uses Xcode's environment variables to execute Dart & Flutter bin. Removed from the following run phase build scripts:
1. uploading debug symbols 
2. bundling service file for iOS build configuration.
I can't write a test as the app needs to be run but I tested locally. Here is the new Run phase build script in Xcode using Xcode environment variables:
Here is the script being executed successfully:
=> fix: remove absolute paths from run phase build script

analysis_options.yaml, packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/commands/reconfigure.dart, packages/flutterfire_cli/lib/src/firebase/firebase_dart_configuration_write.dart, packages/flutterfire_cli/pubspec.yaml, packages/flutterfire_cli/test/configure_test.dart, packages/flutterfire_cli/test/test_utils.dart, packages/flutterfire_starter/hooks/pre_gen.dart
This PR also updates dependencies which fixes this issue: https://github.com/invertase/flutterfire_cli/issues/181
closes https://github.com/invertase/flutterfire_cli/issues/181
This also fixes the `flutterfire configure` command when `web` is not a platform. E.g.
```bash
flutterfire configure --yes --project=dewqqqqkeww --platforms=ios,android --ios-build-config=Debug-development --ios-out=ios/config/dev/GoogleService-Info.plist --android-out=android/app/src/dev/google-services.json --overwrite-firebase-options --yes
```
I thought there was an issue for this but can't seem to find it now, maybe it was a comment somewhere.
=> fix: if web not selected as platform, breaking `flutterfire configure` command

packages/flutterfire_cli/lib/src/flutter_app.dart
Moved the file checks for bundleId so that `AppInfo.xcconfig` file is checked first. This file is present on macOS, not iOS. macOS `project.pbxproj` file contains incorrect bundle ID. It looks like the following for each build variation for Flutter apps created with the latest Flutter SDK:
```
PRODUCT_BUNDLE_IDENTIFIER = com.example.cliFlutterLatest.RunnerTests;
```
Logs from running `flutterfire configure` with this latest change:
```bash
➜  cli_flutter_latest git:(main) ✗ flutterfire configure --project=some-proj --yes
Building package executable... (1.7s)
Built flutterfire_cli_monorepo:flutterfire_dev.
i Found 20 Firebase projects. Selecting project some-proj. …
```
=> fix: macOS bundleId was incorrectly selecting `some.app.RunnerTests`

packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart
fixes https://github.com/invertase/flutterfire_cli/issues/244
=> fix: bundle service file into Contents/Resources for macOS and app root for iOS

packages/flutterfire_cli/lib/src/commands/upload_symbols.dart, packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart
I've tested on two fresh apps using the '--obfuscate' flag. Confirmed that this fixes the Dart stack trace:
also able to see it in the build logs when running: `flutter build --verbose | tee build.log`
```
Running upload-symbols in Build Phase mode
[33mwarning: Flutter build with '--obfuscate' enabled. To view deobfuscated stack traces, upgrade to Flutter 3.12.0+ or upload dSYMs manually using the Firebase console web uploader at https://firebase.google.com/project/_/crashlytics[0m
Validating build environment for Crashlytics...
Processing dSYMs...
Successfully submitted symbols for architecture arm64 with UUID dd9d9a4b88a8358eb1b0beea3f1f8800 in dSYM: /Users/russellwheatley/projects/devTests/third_crash_test/build/ios/Release-iphoneos/Runner.app.dSYM
Successfully submitted symbols for …
```
=> fix(apple): upload debug symbols for de-obfuscating Dart stack traces

packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart, packages/flutterfire_cli/test/configure_test.dart, packages/flutterfire_cli/test/test_utils.dart
fixes https://github.com/invertase/flutterfire_cli/issues/251
there are now 2 legacy ways to update the gradle configuration and the latest Flutter version requires updating the `settings.gradle` file rather than `android/build.gradle` which you can [read more about here](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply). I've refactored the gradle writing to make it clearer what is being updated. Hence why there is now an enum for each different gradle configuration.
I've tested against all three types. At the moment, the CI only tests against the latest and perhaps if there is a bigger use case, I will test against legacy Flutter versions which create different gradle configurations.
Below are the results of running `flutterfire configure --yes …
=> fix(android): another `build.gradle` change in latest flutter (>=3.16.5) when running `flutter create <project>`

packages/flutterfire_cli/lib/src/commands/upload_symbols.dart
fixes: https://github.com/invertase/flutterfire_cli/issues/249
=> fix: ensure Crashlytics Apple upload-symbol script works for every build type/flavor

packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart, packages/flutterfire_cli/test/configure_test.dart, packages/flutterfire_cli/test/test_utils.dart
Wrapped google-services plugin write to check if file already contains `google-services` dependency like we do for other dependency writes; crashlytics and perf mon.
fix: https://github.com/invertase/flutterfire_cli/issues/267
=> fix(android): ensure app/build.gradle only writes google services dependency once

CHANGELOG.md, README.md, packages/flutterfire_cli/CHANGELOG.md, packages/flutterfire_cli/lib/version.g.dart, packages/flutterfire_cli/pubspec.yaml, packages/flutterfire_starter/hooks/pubspec.yaml
=> chore(release): prepare for moving from dev release to stable release.

packages/flutterfire_cli/pubspec.yaml
Updates the `http` package range to allow `>= 1.0.0 <2.0.0`. A version range is necessary as current `pub_updater` depends on `http: ^0.13.5`.
resolves #255
Will follow-up with 2 more PRs to update `pub_updater` and then change `http` version to `^1.2.1`.
=> chore: updated http dependency range

packages/flutterfire_cli/lib/src/commands/config.dart
Fetching project takes some time and 15s always result in a timeout. raised timeout to 1 minute
=> fix: Raised Firebase project fetch timeout to 40 seconds from 15 seconds.

melos.yaml, packages/flutterfire_cli/lib/src/command_runner.dart, packages/flutterfire_cli/lib/src/commands/install.dart, packages/flutterfire_cli/lib/src/common/package.dart, packages/flutterfire_cli/pubspec.yaml, packages/flutterfire_cli/test/install_test.dart, pubspec.yaml
=> feat: install command

packages/flutterfire_cli/lib/src/commands/base.dart, packages/flutterfire_cli/lib/src/commands/config.dart, packages/flutterfire_cli/lib/src/common/config.dart, packages/flutterfire_cli/lib/src/common/global.dart, packages/flutterfire_cli/lib/src/firebase.dart, packages/flutterfire_cli/lib/src/firebase/firebase_project.dart
1. Fixed `resources` so it [defaults to empty object](https://github.com/invertase/flutterfire_cli/pull/329/commits/511dafcb8eba4d45eca44744d1bf619f5c9a93d2) as [confirmed by the user](https://github.com/invertase/flutterfire_cli/issues/328#issuecomment-2248211300).
2. Created global `debugMode` and `logger` which can be used in future issues to help debug issues.
3. Removed duplicate `getProjects()` [call here](https://github.com/invertase/flutterfire_cli/pull/329/commits/a1f84b4398e8af877a7ea1473c7d9ae8cd969265).
4. [Updated logic for getting firebase projects](https://github.com/invertase/flutterfire_cli/pull/329/commits/8cce13bc06dc736f2b7a1b8d020835ca18a514b0) to write to file if JSON file is huge. For users that have more than 400 projects.
fixes …
=> fix: `resources` property can be `null` in newer Firebase projects if no products have been enabled on the project

packages/flutterfire_cli/lib/src/commands/upload_symbols.dart, packages/flutterfire_cli/lib/src/common/strings.dart
related to: https://github.com/invertase/flutterfire_cli/issues/354
=> fix: improve exception message when `firebase.json` is misconfigured

packages/flutterfire_cli/lib/src/commands/upload_symbols.dart, packages/flutterfire_cli/lib/src/common/strings.dart
This is a follow up to #354. It improves the error message for misconfigured `firebase.json` file.
=> fix: add underlyingException to FirebaseJsonException when projectId or appId are missing

packages/flutterfire_cli/lib/src/common/utils.dart, packages/flutterfire_cli/test/unit_test.dart
Fixes #368 
Relax conditions for android package name validations
=> fix: Relax android package name validation

packages/flutterfire_cli/lib/src/common/utils.dart, packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart, packages/flutterfire_cli/lib/src/flutter_app.dart, packages/flutterfire_cli/test/test_utils.dart
fixes [#305 ](https://github.com/invertase/flutterfire_cli/issues/305)
fixes https://github.com/invertase/flutterfire_cli/issues/374
Added support for updating `android/build.gradle.kts`, `android/settings.gradle.kts` and `android/app/build.gradle.kts` files.
Added `RegExp`s, functions to handle Kotlin Gradle DSL files if Groovy Gradle DSL files are not found
We assume that the project does not use a mix of Groovy and Kotlin DSL gradle files.
We check whether the `android/build.gradle` file exists or not. If it exists, the existing code handles updating the files.
If it does not not exist, we proceed to check whether `android/build.gradle.kts` file exists.
If it does, we use Kotlin DSL configuration.
If both configuration files are not found, an Exception is thrown.
=> feat:  support for Gradle Kotlin DSL (Kotlin DSL comes as standard in newly created Flutter projects)

packages/flutterfire_cli/lib/src/firebase/firebase_dart_options.dart, packages/flutterfire_cli/test/firebase_dart_options_test.dart
Updated to support the new output format of `apps:sdkconfig` command introduced in Firebase CLI v13.31.0, which changed from JavaScript to JSON format for web apps.
- https://github.com/firebase/firebase-tools/pull/7833
Old format (before Firebase CLI v13.31.0):
```javascript
firebase.initializeApp({
"projectId": "my-project",
"appId": "1:1234567890:web:abcdef1234567890",
"apiKey": "api-key",
"authDomain": "my-project.firebaseapp.com",
"messagingSenderId": "1234567890",
"measurementId": "G-ABCDEF1234"
});
```
New format (Firebase CLI v13.31.0 and later):
```json
{
"projectId": "my-project",
"appId": "1:1234567890:web:abcdef1234567890",
"apiKey": "api-key",
"authDomain": "my-project.firebaseapp.com",
"messagingSenderId": "1234567890",
"measurementId": "G-ABCDEF1234"
}
```
Updated …
=> fix: Support json format in Firebase options for web for firebase CLI `>=13.31.0`

packages/flutterfire_cli/lib/src/firebase/firebase_apple_writes.dart
Checks if `upload-crashlytics-symbols` script exists and only updates the contents `shell_script` if it exists.
fixes #272
=> fix: unnecessary changes to upload-crashlytics-symbols script each time configure project

packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart, pubspec.yaml
There was an issue where folder ordering by name would think firebase_core-3.3.0 was higher than firebase_core-3.14.0. I used pub_semver to parse the version to make sure we get the latest version. It might look redundant, but I decided to filter out other package folders to make sure we don't parse the version of all the pub cache folders.
=> fix: firebase_core folder order by parsing the version
